name: 'GrapplingHooks'
version: '${project.version}'
main: me.shoobadom.grappling.Grappling
api-version: '1.21'
authors: [ Shoobadom, Yopal, Nikkilectric ]
description: Adds grappling hooks
commands:
  grapple:
    description: Use /grapple help for information
    usage: /<command>
    aliases: [gh, grpl]
